# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/SEREF/Desktop/dersnotlari/4.year/FallTerm/ImageProcessing/HMW/2/PYTHON/forget_pass.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(404, 430)
        MainWindow.setStyleSheet("\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.965909, stop:0 rgba(78, 237, 163, 255), stop:0.248588 rgba(0, 107, 128, 255), stop:0.723164 rgba(48, 150, 223, 255), stop:1 rgba(3, 131, 103, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_pass_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_pass_3.setGeometry(QtCore.QRect(180, 140, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        self.line_pass_3.setFont(font)
        self.line_pass_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_pass_3.setObjectName("line_pass_3")
        self.pBut_send = QtWidgets.QPushButton(self.centralwidget)
        self.pBut_send.setGeometry(QtCore.QRect(60, 310, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pBut_send.setFont(font)
        self.pBut_send.setObjectName("pBut_send")
        self.line_pass_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_pass_2.setGeometry(QtCore.QRect(180, 250, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        self.line_pass_2.setFont(font)
        self.line_pass_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_pass_2.setObjectName("line_pass_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 30, 321, 81))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.line_pass.setGeometry(QtCore.QRect(180, 190, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        self.line_pass.setFont(font)
        self.line_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_pass.setObjectName("line_pass")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setMouseTracking(True)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setLineWidth(1)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 250, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 404, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pBut_send.setText(_translate("MainWindow", "RESET PASSWORD"))
        self.label_3.setText(_translate("MainWindow", "Username"))
        self.label_4.setText(_translate("MainWindow", "FORGET PASSWORD"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#060606;\">Password</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Confirm Password"))

