# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Serefcan/Desktop/Seref/ders notları/Image Processing/Python_Total/process.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1165, 834)
        MainWindow.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 70, 1131, 701))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pb_Blur = QtWidgets.QPushButton(self.page_2)
        self.pb_Blur.setGeometry(QtCore.QRect(690, 60, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Blur.setFont(font)
        self.pb_Blur.setObjectName("pb_Blur")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(0, 60, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(370, 70, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.l_image_3 = QtWidgets.QLabel(self.page_2)
        self.l_image_3.setGeometry(QtCore.QRect(570, 220, 531, 441))
        self.l_image_3.setText("")
        self.l_image_3.setObjectName("l_image_3")
        self.line_factor_3 = QtWidgets.QLineEdit(self.page_2)
        self.line_factor_3.setGeometry(QtCore.QRect(160, 170, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_3.setFont(font)
        self.line_factor_3.setObjectName("line_factor_3")
        self.line_factor_4 = QtWidgets.QLineEdit(self.page_2)
        self.line_factor_4.setGeometry(QtCore.QRect(750, 170, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_4.setFont(font)
        self.line_factor_4.setObjectName("line_factor_4")
        self.l_image_4 = QtWidgets.QLabel(self.page_2)
        self.l_image_4.setGeometry(QtCore.QRect(10, 220, 531, 451))
        self.l_image_4.setText("")
        self.l_image_4.setObjectName("l_image_4")
        self.sb_BlurRow = QtWidgets.QSpinBox(self.page_2)
        self.sb_BlurRow.setGeometry(QtCore.QRect(200, 60, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.sb_BlurRow.setFont(font)
        self.sb_BlurRow.setMaximum(1000)
        self.sb_BlurRow.setSingleStep(10)
        self.sb_BlurRow.setObjectName("sb_BlurRow")
        self.sb_BlurColumn = QtWidgets.QSpinBox(self.page_2)
        self.sb_BlurColumn.setGeometry(QtCore.QRect(590, 60, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.sb_BlurColumn.setFont(font)
        self.sb_BlurColumn.setMaximum(1000)
        self.sb_BlurColumn.setSingleStep(1)
        self.sb_BlurColumn.setObjectName("sb_BlurColumn")
        self.pb_Choose_2 = QtWidgets.QPushButton(self.page_2)
        self.pb_Choose_2.setGeometry(QtCore.QRect(910, 60, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_2.setFont(font)
        self.pb_Choose_2.setObjectName("pb_Choose_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.cb_Filter_2 = QtWidgets.QComboBox(self.page_5)
        self.cb_Filter_2.setGeometry(QtCore.QRect(240, 30, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.cb_Filter_2.setFont(font)
        self.cb_Filter_2.setObjectName("cb_Filter_2")
        self.cb_Filter_2.addItem("")
        self.cb_Filter_2.addItem("")
        self.cb_Filter_2.addItem("")
        self.cb_Filter_2.addItem("")
        self.cb_Filter_2.addItem("")
        self.cb_Filter_2.addItem("")
        self.cb_Filter_2.addItem("")
        self.l_image_15 = QtWidgets.QLabel(self.page_5)
        self.l_image_15.setGeometry(QtCore.QRect(30, 180, 541, 511))
        self.l_image_15.setText("")
        self.l_image_15.setObjectName("l_image_15")
        self.l_image_16 = QtWidgets.QLabel(self.page_5)
        self.l_image_16.setGeometry(QtCore.QRect(600, 180, 541, 511))
        self.l_image_16.setText("")
        self.l_image_16.setObjectName("l_image_16")
        self.line_factor_15 = QtWidgets.QLineEdit(self.page_5)
        self.line_factor_15.setGeometry(QtCore.QRect(130, 130, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_15.setFont(font)
        self.line_factor_15.setObjectName("line_factor_15")
        self.line_factor_16 = QtWidgets.QLineEdit(self.page_5)
        self.line_factor_16.setGeometry(QtCore.QRect(820, 140, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_16.setFont(font)
        self.line_factor_16.setObjectName("line_factor_16")
        self.pb_ApplyFilter_2 = QtWidgets.QPushButton(self.page_5)
        self.pb_ApplyFilter_2.setGeometry(QtCore.QRect(560, 30, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_ApplyFilter_2.setFont(font)
        self.pb_ApplyFilter_2.setObjectName("pb_ApplyFilter_2")
        self.pb_Choose_7 = QtWidgets.QPushButton(self.page_5)
        self.pb_Choose_7.setGeometry(QtCore.QRect(780, 30, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_7.setFont(font)
        self.pb_Choose_7.setObjectName("pb_Choose_7")
        self.stackedWidget.addWidget(self.page_5)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.cb_Transformation = QtWidgets.QComboBox(self.page_4)
        self.cb_Transformation.setGeometry(QtCore.QRect(160, 40, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.cb_Transformation.setFont(font)
        self.cb_Transformation.setObjectName("cb_Transformation")
        self.cb_Transformation.addItem("")
        self.cb_Transformation.addItem("")
        self.cb_Transformation.addItem("")
        self.cb_Transformation.addItem("")
        self.cb_Transformation.addItem("")
        self.le_Trans1 = QtWidgets.QLineEdit(self.page_4)
        self.le_Trans1.setGeometry(QtCore.QRect(0, 630, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Trans1.setFont(font)
        self.le_Trans1.setText("")
        self.le_Trans1.setObjectName("le_Trans1")
        self.sb_Trans1 = QtWidgets.QSpinBox(self.page_4)
        self.sb_Trans1.setGeometry(QtCore.QRect(180, 630, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.sb_Trans1.setFont(font)
        self.sb_Trans1.setMaximum(1000)
        self.sb_Trans1.setSingleStep(10)
        self.sb_Trans1.setObjectName("sb_Trans1")
        self.le_Trans2 = QtWidgets.QLineEdit(self.page_4)
        self.le_Trans2.setGeometry(QtCore.QRect(270, 630, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Trans2.setFont(font)
        self.le_Trans2.setText("")
        self.le_Trans2.setObjectName("le_Trans2")
        self.le_Trans4 = QtWidgets.QLineEdit(self.page_4)
        self.le_Trans4.setGeometry(QtCore.QRect(830, 630, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Trans4.setFont(font)
        self.le_Trans4.setText("")
        self.le_Trans4.setObjectName("le_Trans4")
        self.le_Trans3 = QtWidgets.QLineEdit(self.page_4)
        self.le_Trans3.setGeometry(QtCore.QRect(550, 630, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Trans3.setFont(font)
        self.le_Trans3.setText("")
        self.le_Trans3.setObjectName("le_Trans3")
        self.sb_Trans2 = QtWidgets.QSpinBox(self.page_4)
        self.sb_Trans2.setGeometry(QtCore.QRect(460, 630, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.sb_Trans2.setFont(font)
        self.sb_Trans2.setMaximum(1000)
        self.sb_Trans2.setSingleStep(10)
        self.sb_Trans2.setObjectName("sb_Trans2")
        self.sb_Trans3 = QtWidgets.QSpinBox(self.page_4)
        self.sb_Trans3.setGeometry(QtCore.QRect(740, 630, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.sb_Trans3.setFont(font)
        self.sb_Trans3.setMaximum(1000)
        self.sb_Trans3.setSingleStep(10)
        self.sb_Trans3.setObjectName("sb_Trans3")
        self.sb_Trans4 = QtWidgets.QSpinBox(self.page_4)
        self.sb_Trans4.setGeometry(QtCore.QRect(1020, 630, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.sb_Trans4.setFont(font)
        self.sb_Trans4.setMaximum(1000)
        self.sb_Trans4.setSingleStep(10)
        self.sb_Trans4.setObjectName("sb_Trans4")
        self.pb_ApplyTransform = QtWidgets.QPushButton(self.page_4)
        self.pb_ApplyTransform.setGeometry(QtCore.QRect(640, 40, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_ApplyTransform.setFont(font)
        self.pb_ApplyTransform.setObjectName("pb_ApplyTransform")
        self.line_factor_5 = QtWidgets.QLineEdit(self.page_4)
        self.line_factor_5.setGeometry(QtCore.QRect(140, 130, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_5.setFont(font)
        self.line_factor_5.setObjectName("line_factor_5")
        self.line_factor_6 = QtWidgets.QLineEdit(self.page_4)
        self.line_factor_6.setGeometry(QtCore.QRect(700, 130, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_6.setFont(font)
        self.line_factor_6.setObjectName("line_factor_6")
        self.l_image_5 = QtWidgets.QLabel(self.page_4)
        self.l_image_5.setGeometry(QtCore.QRect(10, 180, 541, 411))
        self.l_image_5.setText("")
        self.l_image_5.setObjectName("l_image_5")
        self.l_image_6 = QtWidgets.QLabel(self.page_4)
        self.l_image_6.setGeometry(QtCore.QRect(500, 170, 531, 401))
        self.l_image_6.setText("")
        self.l_image_6.setObjectName("l_image_6")
        self.pb_Choose_3 = QtWidgets.QPushButton(self.page_4)
        self.pb_Choose_3.setGeometry(QtCore.QRect(900, 40, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_3.setFont(font)
        self.pb_Choose_3.setObjectName("pb_Choose_3")
        self.stackedWidget.addWidget(self.page_4)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pb_Convert = QtWidgets.QPushButton(self.page)
        self.pb_Convert.setGeometry(QtCore.QRect(580, 30, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Convert.setFont(font)
        self.pb_Convert.setObjectName("pb_Convert")
        self.cb_Convert = QtWidgets.QComboBox(self.page)
        self.cb_Convert.setGeometry(QtCore.QRect(290, 30, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.cb_Convert.setFont(font)
        self.cb_Convert.setObjectName("cb_Convert")
        self.cb_Convert.addItem("")
        self.cb_Convert.addItem("")
        self.cb_Convert.addItem("")
        self.cb_Convert.addItem("")
        self.cb_Convert.addItem("")
        self.cb_Convert.addItem("")
        self.cb_Convert.addItem("")
        self.line_factor_7 = QtWidgets.QLineEdit(self.page)
        self.line_factor_7.setGeometry(QtCore.QRect(140, 110, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_7.setFont(font)
        self.line_factor_7.setObjectName("line_factor_7")
        self.line_factor_8 = QtWidgets.QLineEdit(self.page)
        self.line_factor_8.setGeometry(QtCore.QRect(760, 110, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_8.setFont(font)
        self.line_factor_8.setObjectName("line_factor_8")
        self.l_image_7 = QtWidgets.QLabel(self.page)
        self.l_image_7.setGeometry(QtCore.QRect(0, 160, 541, 511))
        self.l_image_7.setText("")
        self.l_image_7.setObjectName("l_image_7")
        self.l_image_8 = QtWidgets.QLabel(self.page)
        self.l_image_8.setGeometry(QtCore.QRect(560, 160, 561, 511))
        self.l_image_8.setText("")
        self.l_image_8.setObjectName("l_image_8")
        self.pb_Choose_4 = QtWidgets.QPushButton(self.page)
        self.pb_Choose_4.setGeometry(QtCore.QRect(860, 30, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_4.setFont(font)
        self.pb_Choose_4.setObjectName("pb_Choose_4")
        self.stackedWidget.addWidget(self.page)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.cb_HMW3 = QtWidgets.QComboBox(self.page_6)
        self.cb_HMW3.setGeometry(QtCore.QRect(260, 30, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.cb_HMW3.setFont(font)
        self.cb_HMW3.setObjectName("cb_HMW3")
        self.cb_HMW3.addItem("")
        self.cb_HMW3.addItem("")
        self.cb_HMW3.addItem("")
        self.cb_HMW3.addItem("")
        self.cb_HMW3.addItem("")
        self.pb_Applyhistog = QtWidgets.QPushButton(self.page_6)
        self.pb_Applyhistog.setGeometry(QtCore.QRect(650, 30, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Applyhistog.setFont(font)
        self.pb_Applyhistog.setObjectName("pb_Applyhistog")
        self.highValue = QtWidgets.QSlider(self.page_6)
        self.highValue.setGeometry(QtCore.QRect(190, 640, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.highValue.setFont(font)
        self.highValue.setMaximum(255)
        self.highValue.setOrientation(QtCore.Qt.Horizontal)
        self.highValue.setObjectName("highValue")
        self.le_Highvalue = QtWidgets.QLineEdit(self.page_6)
        self.le_Highvalue.setGeometry(QtCore.QRect(410, 630, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Highvalue.setFont(font)
        self.le_Highvalue.setObjectName("le_Highvalue")
        self.le_Hist2 = QtWidgets.QLineEdit(self.page_6)
        self.le_Hist2.setGeometry(QtCore.QRect(550, 630, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Hist2.setFont(font)
        self.le_Hist2.setText("")
        self.le_Hist2.setObjectName("le_Hist2")
        self.highValue_2 = QtWidgets.QSlider(self.page_6)
        self.highValue_2.setGeometry(QtCore.QRect(750, 630, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.highValue_2.setFont(font)
        self.highValue_2.setMaximum(255)
        self.highValue_2.setOrientation(QtCore.Qt.Horizontal)
        self.highValue_2.setObjectName("highValue_2")
        self.le_Lowvalue = QtWidgets.QLineEdit(self.page_6)
        self.le_Lowvalue.setGeometry(QtCore.QRect(1010, 630, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Lowvalue.setFont(font)
        self.le_Lowvalue.setObjectName("le_Lowvalue")
        self.le_Hist1 = QtWidgets.QLineEdit(self.page_6)
        self.le_Hist1.setGeometry(QtCore.QRect(10, 640, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Hist1.setFont(font)
        self.le_Hist1.setText("")
        self.le_Hist1.setObjectName("le_Hist1")
        self.line_factor_9 = QtWidgets.QLineEdit(self.page_6)
        self.line_factor_9.setGeometry(QtCore.QRect(120, 100, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_9.setFont(font)
        self.line_factor_9.setObjectName("line_factor_9")
        self.line_factor_10 = QtWidgets.QLineEdit(self.page_6)
        self.line_factor_10.setGeometry(QtCore.QRect(840, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_10.setFont(font)
        self.line_factor_10.setObjectName("line_factor_10")
        self.l_image_9 = QtWidgets.QLabel(self.page_6)
        self.l_image_9.setGeometry(QtCore.QRect(0, 150, 551, 461))
        self.l_image_9.setText("")
        self.l_image_9.setObjectName("l_image_9")
        self.l_image_10 = QtWidgets.QLabel(self.page_6)
        self.l_image_10.setGeometry(QtCore.QRect(580, 150, 561, 461))
        self.l_image_10.setText("")
        self.l_image_10.setObjectName("l_image_10")
        self.pb_Choose_5 = QtWidgets.QPushButton(self.page_6)
        self.pb_Choose_5.setGeometry(QtCore.QRect(890, 30, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_5.setFont(font)
        self.pb_Choose_5.setObjectName("pb_Choose_5")
        self.stackedWidget.addWidget(self.page_6)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.l_image_13 = QtWidgets.QLabel(self.page_8)
        self.l_image_13.setGeometry(QtCore.QRect(20, 120, 551, 541))
        self.l_image_13.setText("")
        self.l_image_13.setObjectName("l_image_13")
        self.l_image_14 = QtWidgets.QLabel(self.page_8)
        self.l_image_14.setGeometry(QtCore.QRect(600, 120, 551, 541))
        self.l_image_14.setText("")
        self.l_image_14.setObjectName("l_image_14")
        self.line_factor_13 = QtWidgets.QLineEdit(self.page_8)
        self.line_factor_13.setGeometry(QtCore.QRect(160, 50, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_13.setFont(font)
        self.line_factor_13.setObjectName("line_factor_13")
        self.line_factor_14 = QtWidgets.QLineEdit(self.page_8)
        self.line_factor_14.setGeometry(QtCore.QRect(790, 50, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_14.setFont(font)
        self.line_factor_14.setObjectName("line_factor_14")
        self.stackedWidget.addWidget(self.page_8)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.cb_Filter = QtWidgets.QComboBox(self.page_7)
        self.cb_Filter.setGeometry(QtCore.QRect(20, 40, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.cb_Filter.setFont(font)
        self.cb_Filter.setObjectName("cb_Filter")
        self.cb_Filter.addItem("")
        self.cb_Filter.addItem("")
        self.cb_Filter.addItem("")
        self.cb_Filter.addItem("")
        self.pb_ApplyFilter = QtWidgets.QPushButton(self.page_7)
        self.pb_ApplyFilter.setGeometry(QtCore.QRect(750, 40, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_ApplyFilter.setFont(font)
        self.pb_ApplyFilter.setObjectName("pb_ApplyFilter")
        self.le_Filter = QtWidgets.QLineEdit(self.page_7)
        self.le_Filter.setGeometry(QtCore.QRect(280, 40, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Filter.setFont(font)
        self.le_Filter.setText("")
        self.le_Filter.setObjectName("le_Filter")
        self.sp_Filter = QtWidgets.QSlider(self.page_7)
        self.sp_Filter.setGeometry(QtCore.QRect(450, 40, 191, 51))
        self.sp_Filter.setMaximum(255)
        self.sp_Filter.setSingleStep(5)
        self.sp_Filter.setOrientation(QtCore.Qt.Horizontal)
        self.sp_Filter.setObjectName("sp_Filter")
        self.le_Filtersb = QtWidgets.QLineEdit(self.page_7)
        self.le_Filtersb.setGeometry(QtCore.QRect(660, 40, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Filtersb.setFont(font)
        self.le_Filtersb.setObjectName("le_Filtersb")
        self.line_factor_11 = QtWidgets.QLineEdit(self.page_7)
        self.line_factor_11.setGeometry(QtCore.QRect(170, 110, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_11.setFont(font)
        self.line_factor_11.setObjectName("line_factor_11")
        self.line_factor_12 = QtWidgets.QLineEdit(self.page_7)
        self.line_factor_12.setGeometry(QtCore.QRect(760, 110, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_12.setFont(font)
        self.line_factor_12.setObjectName("line_factor_12")
        self.l_image_11 = QtWidgets.QLabel(self.page_7)
        self.l_image_11.setGeometry(QtCore.QRect(10, 160, 541, 511))
        self.l_image_11.setText("")
        self.l_image_11.setObjectName("l_image_11")
        self.l_image_12 = QtWidgets.QLabel(self.page_7)
        self.l_image_12.setGeometry(QtCore.QRect(580, 160, 551, 511))
        self.l_image_12.setText("")
        self.l_image_12.setObjectName("l_image_12")
        self.pb_Choose_6 = QtWidgets.QPushButton(self.page_7)
        self.pb_Choose_6.setGeometry(QtCore.QRect(920, 40, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_6.setFont(font)
        self.pb_Choose_6.setObjectName("pb_Choose_6")
        self.stackedWidget.addWidget(self.page_7)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.pb_Choose_8 = QtWidgets.QPushButton(self.page_9)
        self.pb_Choose_8.setGeometry(QtCore.QRect(150, 20, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_8.setFont(font)
        self.pb_Choose_8.setObjectName("pb_Choose_8")
        self.pb_HighPassFilter = QtWidgets.QPushButton(self.page_9)
        self.pb_HighPassFilter.setGeometry(QtCore.QRect(450, 20, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_HighPassFilter.setFont(font)
        self.pb_HighPassFilter.setObjectName("pb_HighPassFilter")
        self.pb_Threshholding = QtWidgets.QPushButton(self.page_9)
        self.pb_Threshholding.setGeometry(QtCore.QRect(840, 20, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Threshholding.setFont(font)
        self.pb_Threshholding.setObjectName("pb_Threshholding")
        self.l_image_17 = QtWidgets.QLabel(self.page_9)
        self.l_image_17.setGeometry(QtCore.QRect(0, 140, 541, 511))
        self.l_image_17.setText("")
        self.l_image_17.setObjectName("l_image_17")
        self.l_image_18 = QtWidgets.QLabel(self.page_9)
        self.l_image_18.setGeometry(QtCore.QRect(570, 150, 541, 511))
        self.l_image_18.setText("")
        self.l_image_18.setObjectName("l_image_18")
        self.line_factor_17 = QtWidgets.QLineEdit(self.page_9)
        self.line_factor_17.setGeometry(QtCore.QRect(120, 90, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_17.setFont(font)
        self.line_factor_17.setObjectName("line_factor_17")
        self.line_factor_18 = QtWidgets.QLineEdit(self.page_9)
        self.line_factor_18.setGeometry(QtCore.QRect(790, 110, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_18.setFont(font)
        self.line_factor_18.setObjectName("line_factor_18")
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.pb_Choose_9 = QtWidgets.QPushButton(self.page_10)
        self.pb_Choose_9.setGeometry(QtCore.QRect(210, 30, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_9.setFont(font)
        self.pb_Choose_9.setObjectName("pb_Choose_9")
        self.l_image_19 = QtWidgets.QLabel(self.page_10)
        self.l_image_19.setGeometry(QtCore.QRect(0, 160, 541, 511))
        self.l_image_19.setText("")
        self.l_image_19.setObjectName("l_image_19")
        self.l_image_20 = QtWidgets.QLabel(self.page_10)
        self.l_image_20.setGeometry(QtCore.QRect(570, 160, 541, 511))
        self.l_image_20.setText("")
        self.l_image_20.setObjectName("l_image_20")
        self.pb_HighPassFilter_2 = QtWidgets.QPushButton(self.page_10)
        self.pb_HighPassFilter_2.setGeometry(QtCore.QRect(710, 30, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_HighPassFilter_2.setFont(font)
        self.pb_HighPassFilter_2.setObjectName("pb_HighPassFilter_2")
        self.line_factor_19 = QtWidgets.QLineEdit(self.page_10)
        self.line_factor_19.setGeometry(QtCore.QRect(110, 110, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_19.setFont(font)
        self.line_factor_19.setObjectName("line_factor_19")
        self.line_factor_20 = QtWidgets.QLineEdit(self.page_10)
        self.line_factor_20.setGeometry(QtCore.QRect(780, 120, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_20.setFont(font)
        self.line_factor_20.setObjectName("line_factor_20")
        self.stackedWidget.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.pb_Choose_10 = QtWidgets.QPushButton(self.page_11)
        self.pb_Choose_10.setGeometry(QtCore.QRect(50, 30, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_10.setFont(font)
        self.pb_Choose_10.setObjectName("pb_Choose_10")
        self.l_image_21 = QtWidgets.QLabel(self.page_11)
        self.l_image_21.setGeometry(QtCore.QRect(0, 210, 541, 481))
        self.l_image_21.setText("")
        self.l_image_21.setObjectName("l_image_21")
        self.l_image_22 = QtWidgets.QLabel(self.page_11)
        self.l_image_22.setGeometry(QtCore.QRect(570, 210, 541, 481))
        self.l_image_22.setText("")
        self.l_image_22.setObjectName("l_image_22")
        self.line_factor_21 = QtWidgets.QLineEdit(self.page_11)
        self.line_factor_21.setGeometry(QtCore.QRect(120, 160, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_21.setFont(font)
        self.line_factor_21.setObjectName("line_factor_21")
        self.line_factor_22 = QtWidgets.QLineEdit(self.page_11)
        self.line_factor_22.setGeometry(QtCore.QRect(790, 160, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_22.setFont(font)
        self.line_factor_22.setText("")
        self.line_factor_22.setObjectName("line_factor_22")
        self.cb_Menu_2 = QtWidgets.QComboBox(self.page_11)
        self.cb_Menu_2.setGeometry(QtCore.QRect(280, 20, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.cb_Menu_2.setFont(font)
        self.cb_Menu_2.setObjectName("cb_Menu_2")
        self.cb_Menu_2.addItem("")
        self.cb_Menu_2.addItem("")
        self.cb_Menu_2.addItem("")
        self.cb_Menu_2.addItem("")
        self.cb_Menu_2.addItem("")
        self.cb_Menu_2.addItem("")
        self.cb_Menu_3 = QtWidgets.QComboBox(self.page_11)
        self.cb_Menu_3.setGeometry(QtCore.QRect(280, 90, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.cb_Menu_3.setFont(font)
        self.cb_Menu_3.setObjectName("cb_Menu_3")
        self.cb_Menu_3.addItem("")
        self.cb_Menu_3.addItem("")
        self.cb_Menu_3.addItem("")
        self.cb_Menu_3.addItem("")
        self.cb_Menu_3.addItem("")
        self.cb_Menu_3.addItem("")
        self.pb_Choose_11 = QtWidgets.QPushButton(self.page_11)
        self.pb_Choose_11.setGeometry(QtCore.QRect(920, 20, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_11.setFont(font)
        self.pb_Choose_11.setObjectName("pb_Choose_11")
        self.pb_Choose_12 = QtWidgets.QPushButton(self.page_11)
        self.pb_Choose_12.setGeometry(QtCore.QRect(920, 90, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_12.setFont(font)
        self.pb_Choose_12.setObjectName("pb_Choose_12")
        self.le_Filter_2 = QtWidgets.QLineEdit(self.page_11)
        self.le_Filter_2.setGeometry(QtCore.QRect(590, 30, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Filter_2.setFont(font)
        self.le_Filter_2.setText("")
        self.le_Filter_2.setObjectName("le_Filter_2")
        self.le_Filter_3 = QtWidgets.QLineEdit(self.page_11)
        self.le_Filter_3.setGeometry(QtCore.QRect(590, 90, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Filter_3.setFont(font)
        self.le_Filter_3.setText("")
        self.le_Filter_3.setObjectName("le_Filter_3")
        self.le_Filter_4 = QtWidgets.QLineEdit(self.page_11)
        self.le_Filter_4.setGeometry(QtCore.QRect(780, 30, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Filter_4.setFont(font)
        self.le_Filter_4.setText("")
        self.le_Filter_4.setObjectName("le_Filter_4")
        self.le_Filter_5 = QtWidgets.QLineEdit(self.page_11)
        self.le_Filter_5.setGeometry(QtCore.QRect(780, 90, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Filter_5.setFont(font)
        self.le_Filter_5.setText("")
        self.le_Filter_5.setObjectName("le_Filter_5")
        self.stackedWidget.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.pb_Choose_13 = QtWidgets.QPushButton(self.page_12)
        self.pb_Choose_13.setGeometry(QtCore.QRect(40, 40, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_13.setFont(font)
        self.pb_Choose_13.setObjectName("pb_Choose_13")
        self.l_image_23 = QtWidgets.QLabel(self.page_12)
        self.l_image_23.setGeometry(QtCore.QRect(30, 210, 531, 451))
        self.l_image_23.setText("")
        self.l_image_23.setObjectName("l_image_23")
        self.l_image_24 = QtWidgets.QLabel(self.page_12)
        self.l_image_24.setGeometry(QtCore.QRect(590, 210, 531, 451))
        self.l_image_24.setText("")
        self.l_image_24.setObjectName("l_image_24")
        self.line_factor_23 = QtWidgets.QLineEdit(self.page_12)
        self.line_factor_23.setGeometry(QtCore.QRect(150, 160, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_23.setFont(font)
        self.line_factor_23.setObjectName("line_factor_23")
        self.line_factor_24 = QtWidgets.QLineEdit(self.page_12)
        self.line_factor_24.setGeometry(QtCore.QRect(790, 160, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_24.setFont(font)
        self.line_factor_24.setText("")
        self.line_factor_24.setObjectName("line_factor_24")
        self.cb_Menu_4 = QtWidgets.QComboBox(self.page_12)
        self.cb_Menu_4.setGeometry(QtCore.QRect(300, 40, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.cb_Menu_4.setFont(font)
        self.cb_Menu_4.setObjectName("cb_Menu_4")
        self.cb_Menu_4.addItem("")
        self.cb_Menu_4.addItem("")
        self.cb_Menu_4.addItem("")
        self.cb_Menu_4.addItem("")
        self.cb_Menu_4.addItem("")
        self.cb_Menu_4.addItem("")
        self.le_Filter_6 = QtWidgets.QLineEdit(self.page_12)
        self.le_Filter_6.setGeometry(QtCore.QRect(630, 20, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Filter_6.setFont(font)
        self.le_Filter_6.setText("")
        self.le_Filter_6.setObjectName("le_Filter_6")
        self.le_Filter_7 = QtWidgets.QLineEdit(self.page_12)
        self.le_Filter_7.setGeometry(QtCore.QRect(820, 20, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Filter_7.setFont(font)
        self.le_Filter_7.setText("")
        self.le_Filter_7.setObjectName("le_Filter_7")
        self.pb_Choose_14 = QtWidgets.QPushButton(self.page_12)
        self.pb_Choose_14.setGeometry(QtCore.QRect(930, 50, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_14.setFont(font)
        self.pb_Choose_14.setObjectName("pb_Choose_14")
        self.le_Filter_8 = QtWidgets.QLineEdit(self.page_12)
        self.le_Filter_8.setGeometry(QtCore.QRect(630, 90, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Filter_8.setFont(font)
        self.le_Filter_8.setText("")
        self.le_Filter_8.setObjectName("le_Filter_8")
        self.le_Filter_9 = QtWidgets.QLineEdit(self.page_12)
        self.le_Filter_9.setGeometry(QtCore.QRect(820, 90, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le_Filter_9.setFont(font)
        self.le_Filter_9.setText("")
        self.le_Filter_9.setObjectName("le_Filter_9")
        self.stackedWidget.addWidget(self.page_12)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.l_image_25 = QtWidgets.QLabel(self.page_13)
        self.l_image_25.setGeometry(QtCore.QRect(20, 250, 531, 451))
        self.l_image_25.setText("")
        self.l_image_25.setObjectName("l_image_25")
        self.l_image_26 = QtWidgets.QLabel(self.page_13)
        self.l_image_26.setGeometry(QtCore.QRect(580, 240, 531, 451))
        self.l_image_26.setText("")
        self.l_image_26.setObjectName("l_image_26")
        self.line_factor_25 = QtWidgets.QLineEdit(self.page_13)
        self.line_factor_25.setGeometry(QtCore.QRect(130, 200, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_25.setFont(font)
        self.line_factor_25.setObjectName("line_factor_25")
        self.line_factor_26 = QtWidgets.QLineEdit(self.page_13)
        self.line_factor_26.setGeometry(QtCore.QRect(700, 190, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_factor_26.setFont(font)
        self.line_factor_26.setText("")
        self.line_factor_26.setObjectName("line_factor_26")
        self.pb_Choose_15 = QtWidgets.QPushButton(self.page_13)
        self.pb_Choose_15.setGeometry(QtCore.QRect(40, 70, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_15.setFont(font)
        self.pb_Choose_15.setObjectName("pb_Choose_15")
        self.pb_Choose_16 = QtWidgets.QPushButton(self.page_13)
        self.pb_Choose_16.setGeometry(QtCore.QRect(390, 70, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_16.setFont(font)
        self.pb_Choose_16.setObjectName("pb_Choose_16")
        self.pb_Choose_17 = QtWidgets.QPushButton(self.page_13)
        self.pb_Choose_17.setGeometry(QtCore.QRect(700, 70, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Choose_17.setFont(font)
        self.pb_Choose_17.setObjectName("pb_Choose_17")
        self.stackedWidget.addWidget(self.page_13)
        self.cb_Menu = QtWidgets.QComboBox(self.centralwidget)
        self.cb_Menu.setGeometry(QtCore.QRect(150, 20, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.cb_Menu.setFont(font)
        self.cb_Menu.setObjectName("cb_Menu")
        self.cb_Menu.addItem("")
        self.cb_Menu.addItem("")
        self.cb_Menu.addItem("")
        self.cb_Menu.addItem("")
        self.cb_Menu.addItem("")
        self.cb_Menu.addItem("")
        self.cb_Menu.addItem("")
        self.cb_Menu.addItem("")
        self.cb_Menu.addItem("")
        self.cb_Menu.addItem("")
        self.cb_Menu.addItem("")
        self.cb_Menu.addItem("")
        self.cb_Menu.addItem("")
        self.pb_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pb_Save.setGeometry(QtCore.QRect(650, 20, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_Save.setFont(font)
        self.pb_Save.setObjectName("pb_Save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1165, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_Blur.setText(_translate("MainWindow", "BLUR IMAGE"))
        self.label.setText(_translate("MainWindow", "ROW SIZE :"))
        self.label_2.setText(_translate("MainWindow", "COLUMN SIZE :"))
        self.line_factor_3.setText(_translate("MainWindow", "ORIGINAL IMAGE"))
        self.line_factor_4.setText(_translate("MainWindow", "BLURED IMAGE"))
        self.pb_Choose_2.setText(_translate("MainWindow", "CHOOSE IMAGE"))
        self.cb_Filter_2.setItemText(0, _translate("MainWindow", "Laplacian"))
        self.cb_Filter_2.setItemText(1, _translate("MainWindow", "Sobel"))
        self.cb_Filter_2.setItemText(2, _translate("MainWindow", "Sharpened Image"))
        self.cb_Filter_2.setItemText(3, _translate("MainWindow", "Sobel Smooth"))
        self.cb_Filter_2.setItemText(4, _translate("MainWindow", "Mask Image"))
        self.cb_Filter_2.setItemText(5, _translate("MainWindow", "Image+Mask"))
        self.cb_Filter_2.setItemText(6, _translate("MainWindow", "Power Low"))
        self.line_factor_15.setText(_translate("MainWindow", "ORIGINAL IMAGE"))
        self.line_factor_16.setText(_translate("MainWindow", "FILTERED IMAGE"))
        self.pb_ApplyFilter_2.setText(_translate("MainWindow", "Apply"))
        self.pb_Choose_7.setText(_translate("MainWindow", "CHOOSE IMAGE"))
        self.cb_Transformation.setItemText(0, _translate("MainWindow", "Reflection on the X-Axis"))
        self.cb_Transformation.setItemText(1, _translate("MainWindow", "Reflection on the Y-Axis"))
        self.cb_Transformation.setItemText(2, _translate("MainWindow", "Reflection on the Both Axis"))
        self.cb_Transformation.setItemText(3, _translate("MainWindow", "Resize Image"))
        self.cb_Transformation.setItemText(4, _translate("MainWindow", "Crop Image"))
        self.pb_ApplyTransform.setText(_translate("MainWindow", "APPLY"))
        self.line_factor_5.setText(_translate("MainWindow", "ORIGINAL IMAGE"))
        self.line_factor_6.setText(_translate("MainWindow", "TRANSFORMATED IMAGE"))
        self.pb_Choose_3.setText(_translate("MainWindow", "CHOOSE IMAGE"))
        self.pb_Convert.setText(_translate("MainWindow", "CONVERT"))
        self.cb_Convert.setItemText(0, _translate("MainWindow", "RGB ---> HSI"))
        self.cb_Convert.setItemText(1, _translate("MainWindow", "RGB ---> GRAY"))
        self.cb_Convert.setItemText(2, _translate("MainWindow", "RGB ---> YIQ"))
        self.cb_Convert.setItemText(3, _translate("MainWindow", "YIQ ---> RGB"))
        self.cb_Convert.setItemText(4, _translate("MainWindow", "RGB ---> HSV"))
        self.cb_Convert.setItemText(5, _translate("MainWindow", "HSV ---> RGB"))
        self.cb_Convert.setItemText(6, _translate("MainWindow", "RGB ---> LAB"))
        self.line_factor_7.setText(_translate("MainWindow", "ORIGINAL IMAGE"))
        self.line_factor_8.setText(_translate("MainWindow", "CONVERTED IMAGE"))
        self.pb_Choose_4.setText(_translate("MainWindow", "CHOOSE IMAGE"))
        self.cb_HMW3.setItemText(0, _translate("MainWindow", "Histogram Stretching"))
        self.cb_HMW3.setItemText(1, _translate("MainWindow", "Histogram Equalization"))
        self.cb_HMW3.setItemText(2, _translate("MainWindow", "Transfer Function"))
        self.cb_HMW3.setItemText(3, _translate("MainWindow", "Add Intensity"))
        self.cb_HMW3.setItemText(4, _translate("MainWindow", "Subtract Intensity"))
        self.pb_Applyhistog.setText(_translate("MainWindow", "Apply"))
        self.line_factor_9.setText(_translate("MainWindow", "ORIGINAL IMAGE"))
        self.line_factor_10.setText(_translate("MainWindow", " IMAGE"))
        self.pb_Choose_5.setText(_translate("MainWindow", "CHOOSE IMAGE"))
        self.line_factor_13.setText(_translate("MainWindow", "Before Histogram"))
        self.line_factor_14.setText(_translate("MainWindow", "After Histogram"))
        self.cb_Filter.setItemText(0, _translate("MainWindow", "Median Filter"))
        self.cb_Filter.setItemText(1, _translate("MainWindow", "Minimum Filter"))
        self.cb_Filter.setItemText(2, _translate("MainWindow", "Maximum Filter"))
        self.cb_Filter.setItemText(3, _translate("MainWindow", "Average Filter"))
        self.pb_ApplyFilter.setText(_translate("MainWindow", "Apply"))
        self.line_factor_11.setText(_translate("MainWindow", "ORIGINAL IMAGE"))
        self.line_factor_12.setText(_translate("MainWindow", "FILTERED IMAGE"))
        self.pb_Choose_6.setText(_translate("MainWindow", "CHOOSE IMAGE"))
        self.pb_Choose_8.setText(_translate("MainWindow", "CHOOSE IMAGE"))
        self.pb_HighPassFilter.setText(_translate("MainWindow", "HIGH PASS FILTER"))
        self.pb_Threshholding.setText(_translate("MainWindow", "THRESHOLDING"))
        self.line_factor_17.setText(_translate("MainWindow", "ORIGINAL IMAGE"))
        self.line_factor_18.setText(_translate("MainWindow", "FILTERED IMAGE"))
        self.pb_Choose_9.setText(_translate("MainWindow", "CHOOSE IMAGE"))
        self.pb_HighPassFilter_2.setText(_translate("MainWindow", "MOIRE PATTERN"))
        self.line_factor_19.setText(_translate("MainWindow", "ORIGINAL IMAGE"))
        self.line_factor_20.setText(_translate("MainWindow", "FILTERED IMAGE"))
        self.pb_Choose_10.setText(_translate("MainWindow", "CHOOSE IMAGE"))
        self.line_factor_21.setText(_translate("MainWindow", "ORIGINAL IMAGE"))
        self.cb_Menu_2.setItemText(0, _translate("MainWindow", "Choose Noise"))
        self.cb_Menu_2.setItemText(1, _translate("MainWindow", "Salt Noise"))
        self.cb_Menu_2.setItemText(2, _translate("MainWindow", "Pepper Noise"))
        self.cb_Menu_2.setItemText(3, _translate("MainWindow", "Gaussian Noise"))
        self.cb_Menu_2.setItemText(4, _translate("MainWindow", "Speckle Noise"))
        self.cb_Menu_2.setItemText(5, _translate("MainWindow", "Salt&Pepper Noise"))
        self.cb_Menu_3.setItemText(0, _translate("MainWindow", "Choose Filter"))
        self.cb_Menu_3.setItemText(1, _translate("MainWindow", "Median Filter"))
        self.cb_Menu_3.setItemText(2, _translate("MainWindow", "Max Filter"))
        self.cb_Menu_3.setItemText(3, _translate("MainWindow", "Min Filter"))
        self.cb_Menu_3.setItemText(4, _translate("MainWindow", "Average Filter"))
        self.cb_Menu_3.setItemText(5, _translate("MainWindow", "Speckle Filter"))
        self.pb_Choose_11.setText(_translate("MainWindow", "APPLY NOISE"))
        self.pb_Choose_12.setText(_translate("MainWindow", "APPLY FILTER"))
        self.pb_Choose_13.setText(_translate("MainWindow", "CHOOSE IMAGE"))
        self.line_factor_23.setText(_translate("MainWindow", "ORIGINAL IMAGE"))
        self.cb_Menu_4.setItemText(0, _translate("MainWindow", "Choose Filter"))
        self.cb_Menu_4.setItemText(1, _translate("MainWindow", "Open Image"))
        self.cb_Menu_4.setItemText(2, _translate("MainWindow", "Close Image"))
        self.cb_Menu_4.setItemText(3, _translate("MainWindow", "Extract Gradient"))
        self.cb_Menu_4.setItemText(4, _translate("MainWindow", "Top Hat Transformation"))
        self.cb_Menu_4.setItemText(5, _translate("MainWindow", "Textual Segmentation"))
        self.pb_Choose_14.setText(_translate("MainWindow", "APPLY FILTER"))
        self.line_factor_25.setText(_translate("MainWindow", "ORIGINAL IMAGE"))
        self.pb_Choose_15.setText(_translate("MainWindow", "CHOOSE IMAGE"))
        self.pb_Choose_16.setText(_translate("MainWindow", "OTSU METHOD"))
        self.pb_Choose_17.setText(_translate("MainWindow", "REGION GROWING"))
        self.cb_Menu.setItemText(0, _translate("MainWindow", "IMAGE PROCESS"))
        self.cb_Menu.setItemText(1, _translate("MainWindow", "BLUR IMAGE"))
        self.cb_Menu.setItemText(2, _translate("MainWindow", "TRANSFORMATIONS"))
        self.cb_Menu.setItemText(3, _translate("MainWindow", "CONVERSIONS"))
        self.cb_Menu.setItemText(4, _translate("MainWindow", "HISTOGRAM"))
        self.cb_Menu.setItemText(5, _translate("MainWindow", "HISTOGRAM GRAPHS"))
        self.cb_Menu.setItemText(6, _translate("MainWindow", "FILTERING"))
        self.cb_Menu.setItemText(7, _translate("MainWindow", "SKELETON"))
        self.cb_Menu.setItemText(8, _translate("MainWindow", "High Pass Filtering"))
        self.cb_Menu.setItemText(9, _translate("MainWindow", "Moire Pattern"))
        self.cb_Menu.setItemText(10, _translate("MainWindow", "Noise&Filter"))
        self.cb_Menu.setItemText(11, _translate("MainWindow", "Noise Reduction"))
        self.cb_Menu.setItemText(12, _translate("MainWindow", "OTSU&Region"))
        self.pb_Save.setText(_translate("MainWindow", "SAVE FINAL IMAGE"))

